### ISSUE TITLE
Date Controls Not Working in 2.0.7

### ISSUE THREAD

**Issue by miqrogroove** [fisharebest/webtrees#3439]
After updating from 2.0.6 to 2.0.7, when I type a date into any date field, none of the beautification occurs and also the calendar control will not populate with the correct date.

For example, I just found a record dated July 1, 1941.  So I typed in "7/1/1941".  It now saves this literal value and displays it on the individual's page as "1941" and never beautifies it to `1 JUL 1941` as expected.  🙁

**Comment by fisharebest** [comment]
I just went to the demo site, added a new fact, typed the date `7/1/1941`.
It was changed automatically to `07 JAN 1941`.
If I change my language from en-GB to en-US, and repeat, the date is changed to "01 JUL 1941".

There was a forum report earlier saying the same thing.

Do you see the problem on the demo site?

**Comment by miqrogroove** [comment]
Dropping the browser cache did not help.

Visited the demo site next.  Same problem.

Using Chrome 84 on Windows 10.  Ad blocker is disabled.

**Comment by miqrogroove** [comment]
Chrome console looks like this:

```
webtrees.min.js?v=2.0.7:1 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.e.persistentToggle (webtrees.min.js?v=2.0.7:1)
    at index.php?route=%2Fdemo-stable%2Ftree%2Fdemo%2Findividual%2Fi199%2FFerdinand-Albert-I-Duke-of-Brunswick-Luneburg:2277
DevTools failed to load SourceMap: Could not load content for https://dev.webtrees.net/demo-stable/public/js/vendor.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by fisharebest** [comment]
I just tried chrome, and that works for me too.

> Cannot read property 'addEventListener' of null at Object.e.persistentToggle

`persistentToggle` isn't used on the edit pages, so I suspect that message belonged to a previous page.

**Comment by miqrogroove** [comment]
Ah here's another...

```
webtrees.min.js?v=2.0.7:1 Uncaught TypeError: o.replaceAll is not a function
    at Object.e.reformatDate (webtrees.min.js?v=2.0.7:1)
    at HTMLInputElement.onchange (59e5284fa317abfd62b68d1e42d4bf42?url=https%3A%2F%2Ffamily.captainslog.aero%2Ftree%2Ftree1%2Findividual%2FI2075%2FJoseph-Francis-Hunter:663)
DevTools failed to load SourceMap: Could not parse content for https://family.captainslog.aero/public/js/vendor.min.js.map: Unexpected token < in JSON at position 1
```

**Comment by fisharebest** [comment]
Which version of chrome do you have?

**Comment by fisharebest** [comment]
https://caniuse.com/#search=replaceAll

**Comment by miqrogroove** [comment]
Yeah that's not going to work on 88% of all computers.

**Comment by TheDutchJewel** [comment]
Same problem here with webtrees 2.0.7 and latest versions of Edge (84.0.522.44) and Firefox (78.0.2). Working fine on 2.0.6.

**Comment by fisharebest** [comment]
I'm looking at babel/polyfill to provide support for older browsers.
I've got the build process working.

It needs some more testing.

**Comment by miqrogroove** [comment]
Tested and working.

**Comment by TheDutchJewel** [comment]
How does this fix work? I copy-pasted the content of the updated [public/js/webtrees.min.js](https://raw.githubusercontent.com/fisharebest/webtrees/4ad647d513adf58792669ecfe5084f4d217b9794/public/js/webtrees.min.js) into the same file on my pc, but it still doesn't do anything when I type a date like `1 1 2000`.

And in the Chrome console of Edge, I see this info:
```
DevTools failed to load SourceMap: Could not parse content for http://localhost/webtrees/public/js/vendor.min.js.map: Unexpected token < in JSON at position 1
Uncaught ReferenceError: valid_date is not defined at HTMLInputElement.onchange
```

**Comment by miqrogroove** [comment]
Save it from this link https://raw.githubusercontent.com/fisharebest/webtrees/master/public/js/webtrees.min.js

Then you have to drop your browser cache or try Ctrl+Shift+R otherwise it is still using the 2.0.7 copy.

**Comment by TheDutchJewel** [comment]
Thanks for the direct link and info.

I cleared the cache, but still same problem: no date beautification.

**Comment by miqrogroove** [comment]
> I copy-pasted the content 

This is very likely to corrupt the file.  If you haven't saved it or performed a checkout then you could also try downloading the whole project from https://github.com/fisharebest/webtrees/archive/master.zip

**Comment by TheDutchJewel** [comment]
Thanks again. I downloaded/extracted this master.zip, but same problem.

**Comment by miqrogroove** [comment]
It may be a problem specific to Edge.  I tried testing Edge 18 and can't even load half the blocks on the front page.  If you find out more it would be appropriate to open a new issue.

**Comment by TheDutchJewel** [comment]
This is not only a problem in Edge (84.0.522.44) but also in Firefox (79.0).

**Comment by melizaa** [comment]
A numeric month is not changed to letters in demo-dev. I use Windows 10 - in Version 84.0.4147.89 (Official Build) (64-bit) and in Google Chrome Version 85.0.4183.38 (Official Build) beta (64-bit).

**Comment by fisharebest** [comment]
@TheDutchJewel 

You report this error:

> ReferenceError: valid_date is not defined

The function `valid_date()` existed in webtrees 2.0.6

But in 2.0.7, it was updated, and renamed to `reformatDate()`.

The text `valid_date` does not exist anywhere in webtrees 2.0.7.

So, if you have it in an error message, then I guess you have a mix of code from 2.0.6 and 2.0.7.

Try re-installing 2.0.7, and then installing the updated version of webtrees.min.js

Also, you reported this error:

> Could not parse content for http://localhost/webtrees/public/js/vendor.min.js.map: Unexpected token < in JSON at position 1

The file `vendor.min.js.map` is not included in any webtrees release.

It must match *exactly* the file `vendor.min.js`.

Delete it?

**Comment by TheDutchJewel** [comment]
@fisharebest 

I reinstalled webtrees 2.0.7 and updated `webtrees.min.js`. Now the `ReferenceError: valid_date is not defined` is gone.

But when input `1 1 2000` as date, webtrees does **not** correct it to `01 JAN 2000`; this worked fine in 2.0.6.

*vendor.min.js.map*
> Could not parse content for http://localhost/webtrees/public/js/vendor.min.js.map: Unexpected token < in JSON at position 1
> The file vendor.min.js.map is not included in any webtrees release.
> It must match exactly the file vendor.min.js.

I get this error about `http://localhost/webtrees/public/js/vendor.min.js.map` in webtrees 2.0.6 and 2.0.7, while this file doesn't exist. The only files in `webtrees/public/js` are `vendor.min.js` and `webtrees.min.js`.

**Comment by fisharebest** [comment]
> But when input `1 1 2000` as date

This was never a supported/documented feature.

If it worked, it was by accident.

Try `1/1/2000` or `1-1-2000` or `1.1.2000`

**Comment by fisharebest** [comment]
> vendor.min.js.map

OK.  Most browsers report "file not found" - which is normal.
Maybe your server configuration is showing a custom 404 page instead of a 404 error response.

Just ignore it.

**Comment by TheDutchJewel** [comment]
>Try 1/1/2000 or 1-1-2000 or 1.1.2000

That works fine. Thank You!

**Comment by melizaa** [comment]
I have filled dates as 1 1 2000 since phpgedview and till lately.
It is faster to hit a space on the keyboard than hitting a / or - or .
Please try to again allow also the spaces.
